name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  audit:
    strategy:
      matrix:
        go: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go vet ./...
      - run: go test -vet=off ./...
      - uses: dominikh/staticcheck-action@v1.4.0
        with:
          install-go: false
